### ISSUE TITLE
Possibility to explore views from BQ

### ISSUE THREAD

**Issue by mar-pan** [bstruct/vscode-bigquery#52]
Hello would it be possible to add viewing option for BQ views in your extension?

**Comment by DamiaoCastro** [comment]
@mar-pan , sure, I will make put it in the next version. Just a tiny note that is not possible to preview views like tables. Preview tables is free of cost. In order to show the view data, same for external tables, internally, a query will be executed, therefore it will have costs. 
Regardless of this detail, agree that it makes sense to have a consistent experience between tables, external tables and views.

**Comment by mar-pan** [comment]
Thanks a lot 😍

**Comment by DamiaoCastro** [comment]
Hi @mar-pan , just added this feature to the new version 0.1.0. Published on open-vsx as well: https://open-vsx.org/extension/bstruct/vscode-bigquery
Please let me know if you bump into any issue.

**Comment by DamiaoCastro** [comment]
The new version is not opening the authentication on code-oss. I will issue a hotfix under 0.1.1
